config/routes.rb
Rails.application.routes.draw do

  root to: "artists#index"
  resources :artists do
  resources :songs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
end

app/models/add_info_to_artist.rb
class AddInfoToArtist < ApplicationRecord
  belongs_to :artist
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy
  has_many :photos, dependent: :destroy

  validates :name, presence: true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :artist

mount_uploader :image, ImageUploader  
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

#adding render to boss
  def show
    @artist = Artist.find(params[:id])
    @song = Song.new
     render json: @artist if params[:format] == 'json'
    end

  def index
      @artists = Artist.all
      @songs = Song.new
    end

  def new
        # @song = Song.new
      end

      # GET /songs/1/edit
  def edit

    end

      # POST /songs
      # POST /songs.json
  def create
       @artist = Artist.new(artist_params)
    if @artist.save
    pictures_params.each do |picture|
      @artist.pictures.create(image_url: picture)
    end
    redirect_to new_artist_song_path(@artist), notice: "Artist created, you can now add a first song or do it later"
  else
    render :new
  end
 end



      # PATCH/PUT /songs/1
      # PATCH/PUT /songs/1.json
    def update
        respond_to do |format|
          if @song.update(song_params)
            format.html { redirect_to @song, notice: 'Song was successfully updated.' }
            format.json { render :show, status: :ok, location: @song }
          else
            format.html { render :edit }
            format.json { render json: @song.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE /songs/1
      # DELETE /songs/1.json
    def destroy
        @song.destroy
        respond_to do |format|
          format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
          format.json { head :no_content }
        end
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_song
          @song = Song.find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
      def song_params
          params.require(:song).permit(:name, :created)
        end
  end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def show
    @artist=current_artist
    @song = current_song
    render json: @song if params[:format] == 'json'
  end
  def new
    @song = current_artist.songs.build
  end

  def create
    @song = current_artist.songs.build(song_params)
    # jsonform, songs_path
    respond_to do |format|
    if @song.save
     format.html { redirect_to artist_path(current_artist), notice: "! created" }
    format.json {render json: {song: @song, status: :created }}
  else

        format.json {render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @song = current_song
    @artist = current_artist
  end

  def update
    if current_song.update(song_params)
      redirect_to artist_path(current_artist), notice: "Song updated"
    else
      render :edit
    end
  end

  def destroy
    current_song = Song.find(params[:id])
    current_song.destroy
    respond_to do |format|
    format.json { render json: {song: @song, status: :deleted}}
  end
end

  private
  def current_song
    @song=Song.find(params[:id])
  end

  def current_artist
    @artist = Artist.find(params[:artist_id])
  end

  def song_params
    params
    .require(:song)
    .permit(:name, :length, :release_date)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<%= form_for ([@artist, @song]) do |f| %>
<%  %>
<div class="form-group">

<%= f.text_field :name, placeholder: "Song", class: "form-control" %>
</div>




<!-- <div class="actions">

    <%= link_to "Add new song", new_artist_song_path(@artist), class: "btn btn-success" %>
</div> -->
<% end %>

app/views/artists/edit.html.erb
<h1>Editing Songs</h1>

<%= render 'form', song: @song %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/artists/index.html.erb
<h1>Artists overview:</h1>



<div class="row">
  <%@artists.each do |artist|%>
  <div class="col-sm-3 col-md-3">
     <div class="thumbnail">
      <%if artist.photos.first%>
      <%= image_tag artist.photos.first.image.thumbnail %>
      <%else%>
      <img alt="Artist picture" style="height: 50px; width: 50px; display: block;"  >
      <%end%>
      <div class="caption">
        <h3><%=artist.name%></h3>
        <p><%= link_to "View", artist, class: "btn btn-success" %> </p>
      </div>
    </div>
  </div>
  <%end%>

app/views/artists/new.html.erb
<h1>New Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Back', songs_path %>

app/views/artists/show.html.erb
a<body>

<h4><li class="sidebar-item"><%= link_to "Artists Overview", artists_path, class: "sidebar-link" %></li>
</h4>
<div class="panel panel-primary">
  <div class="img-circle" alt="Cinque Terre">
  <% @artist.photos.each do |photo| %>
   <div class="panel-heading">
    <%= image_tag photo.image.thumbnail %>
    </div>
<%end%>
</div>
<h3> <%=@artist.name%></h3>

<h4> Age:<%= @artist.age %> </h4>
<h4> Country: <%= @artist.country  %></h4>
<h4> Style: <%= @artist.style %></h4>
<h4> Biography: </h4> <h5><%=   @artist.info %> </h5>
  <a  target="_tab" <%= link_to "More Info? ", @artist.url, class: "btn btn-success"%></a>
</div>

<div class="progress-bar", role="progressbar" aria-valuenow="3"
aria-valuemin="1" aria-valuemax="100" style="width:100%">

  <span class="sr-only"> </span><h2>All Time Hits</h2>
  <iframe width="560" height="315" src= "<%= @artist.video %>" frameborder="1" allowfullscreen></iframe>

</div>

 <table>
<%= render "/songs/form", artist: @artist, song: @song %>
</table>


<div> <%@artist.songs.each do |song| %>
      <h5>  <%= link_to song.name, artist_song_path(@artist, song)%></h5>

  <h5><%= link_to "Delete song", artist_song_path(@artist, song), class: "btn btn-default", method: :delete, data: { confirm: "Are you sure?" }%>


  </div>

  <%end%>


<tr class="song <%= @song.created? ? "success" : "" %>" data-id="<%= @song.id %>">
  <td>
    <input name="song[<%= @song.id %>]" id="song-<%= @song.id %>" type="checkbox" value="1" <%= @song.created? ? 'checked="checked"' : '' %>>
  </td>
  <td>
    <label for="song-<%= @song.id %>"><%= @song.name %></label>
  </td>
</tr>
  </body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AJAX</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/photos/_list.html.erb
<% if @photos %>
  <% @photos.each do |photo| %>
    <div class="panel panel-default">
      <div class="panel-heading preview">
        <%= image_tag photo.image.thumbnail %>
      </div>
      <div class="panel-body">
        <span class="btn btn-default">More photos</span>
      </div>
    </div>
  <% end %>
<% end %>

app/views/songs/_form.html.erb
<%= form_for ([@artist, @song]) do |f| %>
  <div class="form-group" id="formgroup-title">

    <% if @song.errors.full_messages.any? %>
      <% @song.errors.full_messages.each do |error_message| %>
        <div class="alert alert-success" role="alert"><%= error_message%> <br /></div>
      <% end %>
    <% end %>

    <div class="form-group">
    <label>Song list</label>
      <%= f.text_field :name, placeholder: "New song?", class: "form-control" %>
    </div>

  </div>
  <% end %>

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form', song: @song %>

app/views/songs/show.html.erb
<h2>Don't be lazy, look up here:
<%= link_to "YouTube",   href="http://www.youtube.com/", :target => "_blank"%>
</h2>